let timer;
const appRoot = document.querySelector('.content');
const initialView = appRoot.innerHTML;
const icons = {planner:'✦', postgres:'▦', vector:'⌁', investigator:'◌', parallel_investigations:'⇄', approval:'♢', verifier:'✓', report:'≡'};

function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function timeLabel(iso){return new Date(iso).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function setActive(route){document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.getAttribute('href')===`#${route}`))}
function shell(title, eyebrow, body){appRoot.innerHTML=`<div class="page-heading"><div><span class="eyebrow accent">${eyebrow}</span><h1>${title}</h1></div><div class="page-orbit">✦</div></div>${body}`}
function renderNewRun(){appRoot.innerHTML=initialView;setActive('run');bindComposer()}
function render(run){
  const title=document.getElementById('run-title'); if(!title)return;
  title.textContent=run.status==='complete'?'Report ready for review':run.status==='awaiting_approval'?'Approval needed to continue':'Executing your objective';
  document.getElementById('trace-id').textContent=run.id;
  document.getElementById('run-meta').innerHTML=`<span class="live-indicator"></span>${run.status.replace('_',' ')} · ${run.progress}%`;
  document.getElementById('workflow-grid').innerHTML=run.nodes.map(n=>`<div class="workflow-card ${n.status}"><div class="node-top"><div class="node-icon">${icons[n.id]||'•'}</div><span class="node-state">${n.status.toUpperCase()}</span></div><strong>${n.label}</strong><p>${n.detail||'Waiting to start'}</p></div>`).join('');
  document.getElementById('activity-list').innerHTML=run.events.length?run.events.slice().reverse().map(e=>`<div class="activity-item"><time>${timeLabel(e.at)}</time><p><b>${e.agent}</b>${e.message}</p></div>`).join(''):'<div class="empty-state">Starting trail…</div>';
  document.getElementById('evidence-list').innerHTML=run.evidence.length?run.evidence.map(e=>`<div class="evidence-item"><div class="evidence-title"><span>${e.title}</span><span class="confidence">${Math.round(e.confidence*100)}%</span></div><div class="evidence-source">${e.source}</div><p class="evidence-excerpt">“${e.excerpt}”</p></div>`).join(''):'<div class="empty-state">Evidence will be attached when verification finishes.</div>';
  if(run.status==='awaiting_approval')showApproval(run)
}
function showApproval(run){if(document.getElementById('approval-action'))return;const action=document.createElement('div');action.id='approval-action';action.className='approval-banner';action.innerHTML=`<span>♢</span><div><strong>Human approval requested</strong><small>Cogniflow is ready to create customer-facing recommendations.</small></div><button id="approve-btn">Approve & continue</button>`;document.querySelector('.section-heading').after(action);document.getElementById('approve-btn').onclick=async()=>{await fetch(`/api/runs/${run.id}/approve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved:true,note:'Approved in Cogniflow console'})});action.remove();toast('Approval recorded. Workflow resumed.');poll(run.id)}}
async function poll(id){clearTimeout(timer);const response=await fetch(`/api/runs/${id}`);if(!response.ok)return;const run=await response.json();render(run);if(['queued','running','awaiting_approval'].includes(run.status))timer=setTimeout(()=>poll(id),700)}
function bindComposer(){const objective=document.getElementById('objective'),button=document.getElementById('run-button'),approval=document.getElementById('approval');if(!button)return;button.onclick=async()=>{if(objective.value.trim().length<12){toast('Add a little more detail to the objective.');return}button.disabled=true;button.innerHTML='<span>Starting…</span><b>↗</b>';const response=await fetch('/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({objective:objective.value,approval_mode:approval.checked?'required':'autonomous'})});const run=await response.json();toast('Investigation started. Your agents are getting to work.');poll(run.id);button.disabled=false;button.innerHTML='<span>Start investigation</span><b>↗</b>'}}

async function renderHistory(){setActive('history');shell('Run history','YOUR WORKSPACE','<div class="page-intro">Every investigation, one clear trail. Pick up where you left off or open a completed report.</div><div class="history-toolbar"><span class="history-count" id="history-count">Loading runs…</span><button class="filter-button">All runs <span>⌄</span></button></div><div class="history-list" id="history-list"><div class="loading-card">Gathering your investigation history…</div></div>');const res=await fetch('/api/runs');const runs=await res.json();document.getElementById('history-count').textContent=`${runs.length} investigation${runs.length===1?'':'s'}`;document.getElementById('history-list').innerHTML=runs.length?runs.map((run,index)=>`<article class="history-card" style="--delay:${index*45}ms"><div class="history-icon ${run.status}">${run.status==='complete'?'✓':'◌'}</div><div class="history-main"><div class="history-top"><strong>${run.objective}</strong><span class="status-pill ${run.status}">${run.status.replace('_',' ')}</span></div><p>${run.current_node} · ${run.progress}% complete · ${run.approval_mode==='required'?'approval enabled':'autonomous mode'}</p><small>${new Date(run.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})} · ${run.id}</small></div><button class="open-run" data-id="${run.id}">Open <span>↗</span></button></article>`).join(''):'<div class="empty-page"><span>◷</span><strong>No investigations yet</strong><p>Your completed and active runs will appear here.</p></div>';document.querySelectorAll('.open-run').forEach(button=>button.onclick=()=>{location.hash='run';setTimeout(()=>poll(button.dataset.id),0)})}
async function renderAgents(){setActive('agents');shell('Your agent team','THE COGNIFLOW TEAM','<div class="page-intro">Specialists with one job each — coordinated to give you an answer you can trust.</div><div class="agent-grid" id="agent-grid"><div class="loading-card">Loading agent team…</div></div>');const agents=await (await fetch('/api/agents')).json();document.getElementById('agent-grid').innerHTML=agents.map((agent,index)=>`<article class="agent-card ${agent.accent}" style="--delay:${index*60}ms"><div class="agent-card-top"><div class="agent-avatar">${agent.id==='planner'?'✦':agent.id==='verifier'?'✓':agent.id==='research-agent'?'⌁':'◌'}</div><span class="ready-pill"><i></i>${agent.status}</span></div><h3>${agent.name}</h3><p>${agent.role}</p><div class="agent-tools">${agent.tools.map(tool=>`<span>${tool}</span>`).join('')}</div></article>`).join('')}
async function renderSources(){setActive('sources');shell('Your data sources','CONNECTED CONTEXT','<div class="page-intro">Cogniflow can only be as useful as the context you choose to connect.</div><div class="source-summary"><div><span class="summary-number">3</span><span>active sources</span></div><div><span class="summary-number">1</span><span>optional connector</span></div><button class="connect-button">+ Connect a source</button></div><div class="source-list" id="source-list"><div class="loading-card">Checking your connections…</div></div>');const sources=await (await fetch('/api/sources')).json();document.getElementById('source-list').innerHTML=sources.map(source=>`<article class="source-card"><div class="source-icon ${source.status}">${source.icon}</div><div class="source-main"><div><h3>${source.name}</h3><span class="source-type">${source.type}</span></div><p>${source.detail}</p></div><span class="connection-status ${source.status}"><i></i>${source.status}</span><button class="source-menu">•••</button></article>`).join('')}
function route(){clearTimeout(timer);const route=location.hash.replace('#','')||'run';if(route==='history')renderHistory();else if(route==='agents')renderAgents();else if(route==='sources')renderSources();else renderNewRun()}
window.addEventListener('hashchange',route);route();
