"""Scope evidence references per customer

Evidence references (`EV-1`, `EV-2`, …) were unique per run, and allocated by
counting the run's existing evidence rows. Under real parallel workers two
concurrent investigations read the same count and both tried to insert the same
reference, violating `uq_evidence_run_reference`. The bug was invisible to the
in-process executor, which runs tasks serially.

References are now allocated — and unique — per (run, customer). One customer is
investigated by exactly one task, so the allocation needs no locking, and the
numbering is more readable: EV-1 is that account's first evidence record.

Hand-written rather than autogenerated: `--autogenerate` does not know about the
HNSW index on `document_chunks.embedding` (created with raw SQL in 0001) and
would propose dropping it.

Revision ID: 0002_scope_evidence_refs
Revises: 0001_initial_schema
"""

from __future__ import annotations

from alembic import op

revision = "0002_scope_evidence_refs"
down_revision = "0001_initial_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_constraint("uq_evidence_run_reference", "evidence", type_="unique")
    op.create_unique_constraint(
        "uq_evidence_run_customer_reference",
        "evidence",
        ["run_id", "customer_id", "reference"],
    )


def downgrade() -> None:
    op.drop_constraint("uq_evidence_run_customer_reference", "evidence", type_="unique")
    op.create_unique_constraint("uq_evidence_run_reference", "evidence", ["run_id", "reference"])
